# Generated by Django 4.0.4 on 2022-05-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTFIDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=40)),
                ('fileName', models.CharField(max_length=10)),
                ('TFIDF', models.FloatField()),
            ],
            options={
                'db_table': 'booktfidf',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='booktfidf',
            constraint=models.UniqueConstraint(fields=('term', 'fileName'), name='unique_token'),
        ),
    ]
